// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZwXJngIKOKmDk1rz5RRHvnDJiZbV0sM',
    appId: '1:844631418134:web:540b3a3296b0cad38a1c37',
    messagingSenderId: '844631418134',
    projectId: 'trustbus-3e2fe',
    authDomain: 'trustbus-3e2fe.firebaseapp.com',
    storageBucket: 'trustbus-3e2fe.firebasestorage.app',
    measurementId: 'G-ZWG7J94VP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5O18g0imMRCMDpWgUdSk5DVP0MtqT2Us',
    appId: '1:844631418134:android:877cb04342d2a83e8a1c37',
    messagingSenderId: '844631418134',
    projectId: 'trustbus-3e2fe',
    storageBucket: 'trustbus-3e2fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTZwXJngIKOKmDk1rz5RRHvnDJiZbV0sM',
    appId: '1:844631418134:web:a55905079e3db9538a1c37',
    messagingSenderId: '844631418134',
    projectId: 'trustbus-3e2fe',
    authDomain: 'trustbus-3e2fe.firebaseapp.com',
    storageBucket: 'trustbus-3e2fe.firebasestorage.app',
    measurementId: 'G-K5F6W6X6XC',
  );
}
